using System.Collections.Generic;

namespace QFramework.ProjectGungeon
{
    public class Lv1Rooms
    {

        //普通敌人房间
        public static List<RoomConfig> NormalRooms = new List<RoomConfig>()
        {
              new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1                 1")
                .L("1                 1")
                .L("1  1           1  1")
                .L("1                 1")
                .L("1                 1")
                .L("1     e     e     1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d       e e       d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1     e     e     1")
                .L("1                 1")
                .L("1                 1")
                .L("1  1           1  1")
                .L("1                 1")
                .L("1                 1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1                 1")
                .L("1                 1")
                .L("1  11         11  1")
                .L("1  1e    e    e1  1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1        e        1")
                .L("d   e   e e   e   d")
                .L("1        e        1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1  1e    e    e1  1")
                .L("1  11         11  1")
                .L("1                 1")
                .L("1                 1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1                 1")
                .L("1  e           e  1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1       e e       1")
                .L("1        e        1")
                .L("d       e1e       d")
                .L("1        e        1")
                .L("1       e e       1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1  e           e  1")
                .L("1                 1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1e               e1")
                .L("1                 1")
                .L("1  1111111111111  1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d       e e       d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1  1111111111111  1")
                .L("1 e             e 1")
                .L("1e               e1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111d111111")
                .L("1           1")
                .L("1           1")
                .L("1  11   11  1")
                .L("1   e   e   1")
                .L("1     e     1")
                .L("d    e e    d")
                .L("1     e     1")
                .L("1   e   e   1")
                .L("1  11   11  1")
                .L("1           1")
                .L("1           1")
                .L("111111d111111"),
        };
    }
}
