using System.Collections.Generic;

namespace QFramework.ProjectGungeon
{
    public class Lv2Rooms
    {

        //普通敌人房间
        public static List<RoomConfig> NormalRooms = new List<RoomConfig>()
        {
             new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111111d111111111111")
                .L("1bb                   bb1")
                .L("1b                     b1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1     1           1     1")
                .L("1                       1")
                .L("1                       1")
                .L("1        e     e        1")
                .L("1         e   e         1")
                .L("1           e           1")
                .L("d          e e          d")
                .L("1           e           1")
                .L("1         e   e         1")
                .L("1        e     e        1")
                .L("1                       1")
                .L("1                       1")
                .L("1     1           1     1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1bb                   bb1")
                .L("1b                     b1")
                .L("111111111111d111111111111"),
             new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1bb               1")
                .L("1  e           e  1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d      e   e      d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1  e           e  1")
                .L("1               bb1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1               bb1")
                .L("1   e         e  b1")
                .L("1      11111      1")
                .L("1       bbb       1")
                .L("1                 1")
                .L("1                 1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d       e e       d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1                 1")
                .L("1                 1")
                .L("1       bbb       1")
                .L("1      11111      1")
                .L("1b  e         e   1")
                .L("1bb               1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111111d111111111111")
                .L("1bb                   bb1")
                .L("1b                     b1")
                .L("1  11               11  1")
                .L("1  1       e         1  1")
                .L("1    e             e    1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1            e          1")
                .L("1                       1")
                .L("d     e    e   e   e    d")
                .L("1                       1")
                .L("1            e          1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1   e               e   1")
                .L("1  1       e         1  1")
                .L("1  11               11  1")
                .L("1                       1")
                .L("1   bbb           bbb   1")
                .L("111111111111d111111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("11111111111d11111111111")
                .L("1bbb               bbb1")
                .L("1          e          1")
                .L("1                     1")
                .L("1          1          1")
                .L("d     e   111    e    d")
                .L("1          1          1")
                .L("1                     1")
                .L("1b          e        b1")
                .L("1bb                 bb1")
                .L("11111111111d11111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("11111111111d11111111111")
                .L("1                     1")
                .L("1  e               e  1")
                .L("1                     1")
                .L("1                     1")
                .L("1bbb               bbb1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1        e   e        1")
                .L("1          e          1")
                .L("d        e   e        d")
                .L("1          e          1")
                .L("1        e   e        1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1bbb               bbb1")
                .L("1                     1")
                .L("1 e                e  1")
                .L("1                     1")
                .L("1                     1")
                .L("11111111111d11111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1                 1")
                .L("1  e           e  1")
                .L("1        e        1")
                .L("1                 1")
                .L("1                 1")
                .L("1        bb       1")
                .L("1      bbbbbb     1")
                .L("1     bbbbbbbb    1")
                .L("d    bbbbbbbbbb   d")
                .L("1     bbbbbbbb    1")
                .L("1      bbbbbb     1")
                .L("1        bb       1")
                .L("1                 1")
                .L("1                 1")
                .L("1        e        1")
                .L("1  e           e  1")
                .L("1                 1")
                .L("111111111d111111111"),
        };
    }
}
