using System.Collections.Generic;

namespace QFramework.ProjectGungeon
{
    public class Lv3Rooms
    {
        public static List<RoomConfig> NormalRooms = new List<RoomConfig>()
        {
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111111d111111111111")
                .L("1b                     b1")
                .L("1b                     b1")
                .L("1bb                   bb1")
                .L("111111             111111")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1        e     e        1")
                .L("1         e   e         1")
                .L("1           e           1")
                .L("d          e e          d")
                .L("1           e           1")
                .L("1         e   e         1")
                .L("1        e     e        1")
                .L("1                       1")
                .L("1                       1")
                .L("1                       1")
                .L("1    1             1    1")
                .L("1    1             1    1")
                .L("1    1             1    1")
                .L("1    1             1    1")
                .L("1                       1")
                .L("1                       1")
                .L("111111111111d111111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111111d111111111111")
                .L("1                       1")
                .L("1                       1")
                .L("1  1                 1  1")
                .L("1                       1")
                .L("1   e       e       e   1")
                .L("1                       1")
                .L("1b                     b1")
                .L("1b                     b1")
                .L("1bb                   bb1")
                .L("1                       1")
                .L("1           e           1")
                .L("d   e      e e      e   d")
                .L("1           e           1")
                .L("1                       1")
                .L("1bb                   bb1")
                .L("1b                     b1")
                .L("1b                     b1")
                .L("1                       1")
                .L("1   e       e       e   1")
                .L("1                       1")
                .L("1  1                 1  1")
                .L("1                       1")
                .L("1                       1")
                .L("111111111111d111111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("11111111111d11111111111")
                .L("1                     1")
                .L("1          e          1")
                .L("1                     1")
                .L("d      e   1   e      d")
                .L("1                     1")
                .L("1          e          1")
                .L("1                     1")
                .L("11111111111d11111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("11111111111d11111111111")
                .L("1                     1")
                .L("1  e               e  1")
                .L("1                     1")
                .L("1bb                 bb1")
                .L("1b                   b1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1        e   e        1")
                .L("1          e          1")
                .L("d         e e         d")
                .L("1          e          1")
                .L("1        e   e        1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1                     1")
                .L("1 e                e  1")
                .L("1                     1")
                .L("1                     1")
                .L("11111111111d11111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1bb               1")
                .L("1  e           e  1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d      e   e      d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1                 1")
                .L("1  e           e  1")
                .L("1               bb1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("111111111d111111111")
                .L("1               bb1")
                .L("1   e         e  b1")
                .L("1      11111      1")
                .L("1       bbb       1")
                .L("1                 1")
                .L("1                 1")
                .L("1      e   e      1")
                .L("1        e        1")
                .L("d       e e       d")
                .L("1        e        1")
                .L("1      e   e      1")
                .L("1                 1")
                .L("1                 1")
                .L("1       bbb       1")
                .L("1      11111      1")
                .L("1b  e         e   1")
                .L("1bb               1")
                .L("111111111d111111111"),
            new RoomConfig()
                .Type(RoomTypes.Normal)
                .L("11111111111d11111111111")
                .L("1                     1")
                .L("1  e               e  1")
                .L("1          e          1")
                .L("1                     1")
                .L("1                     1")
                .L("1         bbbb        1")
                .L("1       bbbbbbbb      1")
                .L("1     bbbbbbbbbbbb    1")
                .L("d    bbbbbbbbbbbbbb   d")
                .L("1     bbbbbbbbbbbb    1")
                .L("1       bbbbbbbb      1")
                .L("1         bbbb        1")
                .L("1                     1")
                .L("1                     1")
                .L("1          e          1")
                .L("1  e               e  1")
                .L("1                     1")
                .L("11111111111d11111111111"),
        };
    }
}